name: BorderPatrol
version: @VERSION@
description: Limits player movement past a rectangular boundary
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/BorderPatrol
main: edgruberman.bukkit.borderpatrol.Main
commands:
    'borderpatrol:reload':
        description: Reload BorderPatrol plugin
        permission: borderpatrol.reload
        usage: /<command>
permissions:
    borderpatrol.reload:
        description: Can use reload command
        default: op