name: @NAME@
description: Limits player movement past a rectangular boundary
softdepend: [TimeService]
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'borderpatrol:reload':
        description: Reload BorderPatrol plugin
        permission: borderpatrol.reload
        usage: /<command>
permissions:
    borderpatrol.reload:
        description: Can use reload command
        default: op