name: SimpleBorder
description: Limits player movement past a defined square border.
version: %VERSION%
depend: [MessageManager]
author: EdGruberman (ed@rjump.com)
main: edgruberman.bukkit.simpleborder.Main