message: 'You have been returned inside the border'
borders:
    worldName:
        minX: -1000
        maxX: 1000
        minZ: -1000
        maxZ: 1000
        safe:
            x: 0
            y: 64
            z: 0
logLevel: INFO
version: @VERSION@